### ISSUE TITLE
Files won't download.

### ISSUE THREAD

**Issue by s12227054** [DisboxApp/web#18]
I uploaded a ZIP file, but when I went to download it again, I got the following error:
Failed to download file: TypeError: window.showSaveFilePicker is not a function.
I am on Windows 11, using Firefox 108.0.1.

**Comment by DisboxApp** [comment]
Hey, thanks for reporting!
This is a known issue - the File System Access API and it's methods are experimental and are not fully supported on all platforms: https://developer.mozilla.org/en-US/docs/Web/API/window/showSaveFilePicker#browser_compatibility

Disbox uses it and not a stable API because it doesn't need to save the entire file in memory, which allows downloading files of any size (otherwise you're limited to a browser's tab memory limit (which on Chrome is anywhere between 500MB to 4GB).

There are other, also experimental ways of doing this which support more browsers (https://github.com/jimmywarting/native-file-system-adapter), but I couldn't get them to work. I do have plans to try using it again, because waiting for browser standards to mature may take too long - but those are in the far future as it's not a priority right now.

If you have a solution for this/can get the adapter to work, please follow up here or open a separate PR - but for now, I'm closing this issue.
