### ISSUE TITLE
The file list totally different when i visit using different browsers.

### ISSUE THREAD

**Issue by hb8t** [DisboxApp/web#75]
I used 4 browsers: 3 on the same Linux system, firefox, brave, chromium; and the other is firefox on a linux VM. I attempted to upload some files from them. Strangely i see a different list of files (some being vacant lists) using these diff browsers.

**Comment by MT-276** [comment]
The first thought that comes to my mind is that whether you use more than one webhooks, i.e. data storing channels. If so, then I think you have different webhooks stored for different browsers.\
Disbox probably uses cookies to save your last entered webhook instead of an IP log. Hence it must be different for different browsers.\
Again, this is just my opinion. This may very well be a genuine issue.

**Comment by DisboxApp** [comment]
That is correct. Webhooks are stored in the local storage. You can change the webhook by going to the Setup page.
