### ISSUE TITLE
Embedded URL to Enter Your JavaScript and our Discord Webhook

### ISSUE THREAD

**Issue by starzspirit** [DisboxApp/web#91]
Good mornin', and thanks so much for making this awesome tool!

We're transitioning from TeamSpeak to Discord, and one of the features we like to use is the File Transfer option to easily share mods, photos, and videos from time-to-time. Your tool provides this almost seamlessly for us on Discord, however I was wondering if there is a way to get a single link that you can click on that will start your JavaScript with our generated webhook already loaded?

Respectfully,

   Starz

**Comment by DisboxApp** [comment]
Hey, this already exists, but just for a single file (using the share button), but not for the entire drive - for security reasons:

Think about it like this: Your webhook URL is like your password, as it gives full access to your files (in fact, it's even more than a password since there's no username) - you wouldn't want a google drive/dropbox link that has your password in it and gives everyone full access to your account. Instead, it makes more sense to share only what you need.

It would be better if the share feature worked for directories, but that's not really possible with Disbox's architecture.

Hope this helps, feel free to re-open if needed :)
